// GENERATED by scripts/gen-db-types.mjs from docs/schema-history/*.sql — do not edit by hand.

export type Row = { id: string }

export type TableName =
  | 'agency_credentials'
  | 'approvals'
  | 'asana_events'
  | 'asana_project_map'
  | 'asana_tasks'
  | 'asana_webhooks'
  | 'asset_clicks'
  | 'asset_versions'
  | 'assets'
  | 'assistant_chats'
  | 'assistant_prefs'
  | 'batch_comments'
  | 'batches'
  | 'board_comments'
  | 'board_items'
  | 'boards'
  | 'booking_availability'
  | 'booking_blackouts'
  | 'booking_resources'
  | 'booking_seats'
  | 'booking_services'
  | 'bookings'
  | 'calendar_accounts'
  | 'claim_locks'
  | 'client_agreements'
  | 'client_brand'
  | 'client_contacts'
  | 'client_credentials'
  | 'client_notes'
  | 'clients'
  | 'content_applications'
  | 'content_assets'
  | 'content_items'
  | 'deliverable_groups'
  | 'drive_connection'
  | 'drive_files'
  | 'drive_uploads'
  | 'email_ingest_log'
  | 'encode_jobs'
  | 'intake_files'
  | 'intake_forms'
  | 'intake_settings'
  | 'intake_templates'
  | 'item_comments'
  | 'journal_posts'
  | 'leads'
  | 'monthly_commitments'
  | 'monthly_updates'
  | 'newsletter_subscribers'
  | 'notification_log'
  | 'post_analytics'
  | 'projects'
  | 'provider_webhooks'
  | 'publish_jobs'
  | 'report_settings'
  | 'room_invite_requests'
  | 'scan_mailboxes'
  | 'scan_runs'
  | 'scan_settings'
  | 'schedule_entries'
  | 'schedule_notes'
  | 'shoot_proposals'
  | 'social_accounts'
  | 'social_posts'
  | 'team_invites'
  | 'team_user_clients'
  | 'team_users'
  | 'user_page_access'
  | 'video_previews'
  | 'webhook_deliveries'
  | 'website'
  | 'work_kinds'
  | 'workflow_activity'

export interface AgencyCredential {
  id: string
  created_at: string
  updated_at: string
  platform: string
  label: string
  username: string
  secret_cipher: string | null
  url: string
  notes: string
  updated_by: string | null
  updated_by_name: string
}

export interface Approval {
  id: string
  created_at: string
  item_id: string | null
  batch_id: string | null
  approval_type: string
  decided_by: string | null
  decision: string
  notes: string | null
}

export interface AsanaEvent {
  id: string
  dedup_key: string
  created_at: string
  ingested_at: string
  source: string
  user_gid: string | null
  resource_gid: string
  resource_type: string
  action: string
  change_field: string | null
  project_gid: string | null
  raw: unknown
}

export interface AsanaProjectMap {
  project_gid: string
  project_name: string
  client_id: string | null
  tracked: boolean
  created_at: string
  id: string
}

export interface AsanaTask {
  gid: string
  name: string
  assignee_gid: string | null
  project_gid: string | null
  completed: boolean
  completed_at: string | null
  due_on: string | null
  modified_at: string | null
  synced_at: string
  permalink_url: string | null
  id: string
}

export interface AsanaWebhook {
  id: string
  created_at: string
  project_gid: string
  webhook_gid: string | null
  hook_secret: string | null
  sync_token: string | null
  last_heartbeat_at: string | null
  last_event_at: string | null
  last_error: string | null
}

export interface AssetClick {
  id: string
  asset_id: string
  click_id: string
  referrer: string | null
  user_agent: string | null
  clicked_at: string
}

export interface AssetVersion {
  id: string
  created_at: string
  item_id: string
  version_number: number
  file_url: string
  dropbox_url: string
  drive_url: string
  notes: string | null
  uploaded_by: string | null
  files: unknown | null
  cover_url: string | null
  trim_start: number | null
  trim_end: number | null
  source: string | null
  source_drive_file_id: string | null
}

export interface Asset {
  id: string
  created_at: string
  client_id: string | null
  project_id: string | null
  kind: string
  orientation: string | null
  purpose: string | null
  url: string
  alt: string | null
}

export interface AssistantChat {
  id: string
  created_at: string
  updated_at: string
  clerk_user_id: string
  title: string
  messages: unknown
}

export interface AssistantPref {
  clerk_user_id: string
  email: string
  instructions: string
  updated_at: string
  updated_by: string
  id: string
}

export interface BatchComment {
  id: string
  created_at: string
  batch_id: string
  author_id: string | null
  body: string
  assigned_to: string | null
  resolved: boolean | null
}

export interface Batch {
  status: string | null
  concept: string | null
  location: string | null
  shot_list: unknown | null
  planned_deliverables: unknown | null
  reference_media: unknown | null
  locked_at: string | null
  locked_by: string | null
  shot_at: string | null
  proposal_id: string | null
  share_board: boolean | null
  board_name: string | null
  last_edited_by: string | null
  last_edited_at: string | null
  canvas_cards: unknown | null
  drive_folder_id: string | null
  drive_url: string | null
  shared_with_client: boolean | null
  id: string
  created_at: string
  updated_at: string
  client_id: string
  title: string
  description: string | null
  shoot_date: string | null
  month: number | null
  year: number | null
  owner_id: string | null
}

export interface BoardComment {
  id: string
  board_id: string
  item_id: string
  author_id: string | null
  author_name: string
  author_role: string
  body: string
  created_at: string
  resolved_at: string | null
}

export interface BoardItem {
  id: string
  board_id: string
  kind: string
  x: number
  y: number
  w: number
  h: number
  z: number
  colour: string | null
  text: string | null
  url: string | null
  label: string | null
  child_board_id: string | null
  column_title: string | null
  parent_item_id: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}

export interface Board {
  id: string
  client_id: string
  parent_board_id: string | null
  item_id: string | null
  name: string
  icon: string
  colour: string
  created_by: string | null
  created_at: string
  updated_at: string
}

export interface BookingAvailability {
  id: string
  resource_id: string
  weekday: number
  start_min: number
  end_min: number
}

export interface BookingBlackout {
  id: string
  resource_id: string
  day: string
  reason: string | null
}

export interface BookingResource {
  id: string
  created_at: string
  label: string
  email: string | null
  timezone: string
  active: boolean
  space_id: string | null
}

export interface BookingSeat {
  id: string
}

export interface BookingService {
  id: string
  created_at: string
  name: string
  slug: string
  description: string | null
  duration_min: number
  price_cents: number
  currency: string
  active: boolean
  sort_order: number
  policy_text: string | null
  resource_id: string | null
  lead_time_min: number | null
  horizon_days: number | null
  requires_payment: boolean | null
  image_url: string | null
  location: string | null
  category: string | null
  capacity: number | null
}

export interface Booking {
  id: string
  created_at: string
  service_id: string | null
  resource_id: string
  start_at: string
  end_at: string
  customer_name: string
  customer_email: string
  customer_phone: string | null
  notes: string | null
  status: string
  payment_status: string
  payment_ref: string | null
  amount_cents: number
  policy_agreed_at: string | null
  checkout_ref: string | null
  public_ref: string | null
  seat_no: number | null
  space_id: string | null
}

export interface CalendarAccount {
  email: string
  refresh_token_encrypted: string | null
  enabled: boolean
  connected_at: string | null
  connected_by: string | null
  created_at: string
  id: string
}

export interface ClaimLock {
  id: string
}

export interface ClientAgreement {
  id: string
  created_at: string
  updated_at: string
  client_id: string
  deliverable_lines: unknown
  services: unknown
  notes: string | null
  updated_by: string | null
  start_date: string | null
}

export interface ClientBrand {
  client_id: string
  updated_at: string
  updated_by: string
  profile: unknown
  docs: unknown
  scan_status: string | null
  scan_done: number | null
  scan_total: number | null
  scan_message: string | null
  scan_started_at: string | null
  id: string
}

export interface ClientContact {
  id: string
  created_at: string
  updated_at: string
  client_id: string
  name: string
  role: string
  email: string
  phone: string
  is_primary: boolean
  notes: string
}

export interface ClientCredential {
  id: string
  created_at: string
  updated_at: string
  client_id: string
  platform: string
  label: string
  username: string
  secret_cipher: string | null
  url: string
  notes: string
  updated_by: string | null
  updated_by_name: string
}

export interface ClientNote {
  id: string
  created_at: string
  updated_at: string
  client_id: string
  body: string
  author_id: string | null
  author_name: string
  visibility: string | null
}

export interface Client {
  brand_profile: unknown | null
  brand_profile_updated_at: string | null
  brand_profile_updated_by: string | null
  timezone: string | null
  website: string | null
  source: string | null
  share_token: string | null
  social_profile_id: string | null
  id: string
  created_at: string
  name: string
  slug: string
  industry: string | null
  contact_name: string | null
  email: string | null
  phone: string | null
  clerk_user_id: string | null
  status: string
  notes: string | null
  instagram_locations: unknown
  client_approval_required: boolean | null
  drive_folder_id: string | null
  drive_folder_origin: string | null
}

export interface ContentApplication {
  id: string
  created_at: string
  first_name: string
  last_name: string
  email: string
  phone: string
  business: string
  industry: string | null
  model_interest: string | null
  content_needed: string | null
  budget: string | null
  timeline: string | null
}

export interface ContentAsset {
  id: string
  client_id: string | null
  title: string
  platform: string | null
  slug: string
  dest_url: string | null
  post_url: string | null
  provider_post_id: string | null
  source: string
  offer_code: string | null
  keyword: string | null
  published_at: string | null
  created_at: string
}

export interface ContentItem {
  group_id: string | null
  drive_folder_id: string | null
  drive_url: string | null
  posting_approval_state: string
  id: string
  created_at: string
  updated_at: string
  client_id: string
  batch_id: string | null
  title: string
  content_type: string
  platform_targets: string
  status: string
  owner_id: string | null
  due_date: string | null
  priority: string
  caption: string | null
  client_approval_required: boolean
  current_version_number: number
  raw_assets_url: string | null
  brief: string | null
  raw_assets: unknown | null
  scheduler_ids: unknown | null
  brief_url: string | null
  work_kind_id: string | null
}

export interface DeliverableGroup {
  id: string
  client_id: string
  batch_id: string | null
  content_type: string
  title: string
  target: number
  work_kind_id: string | null
  created_by: string | null
  created_at: string
  planned: unknown | null
}

export interface DriveConnection {
  id: string
  account_email: string | null
  account_name: string | null
  refresh_token_encrypted: string | null
  root_name: string
  root_folder_id: string | null
  connected_by: string | null
  connected_at: string | null
  created_at: string
  root_folder_name: string | null
  root_owner_email: string | null
  root_origin: string | null
  root_picked_at: string | null
  root_picked_by: string | null
  clients_folder_id: string | null
  root_account_changed: boolean | null
}

export interface DriveFile {
  parent_id: string | null
  name: string | null
  uploaded_by: string | null
  moved_at: string | null
  id: string
  item_id: string | null
  client_id: string | null
  source_url: string
  target: string
  drive_file_id: string | null
  drive_url: string | null
  bytes: number | null
  created_at: string
}

export interface DriveUpload {
  id: string
  upload_uri: string
  name: string
  parent_id: string
  mime_type: string | null
  size: number | null
  received: number
  client_id: string | null
  status: string
  drive_file_id: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}

export interface EmailIngestLog {
  id: string
  created_at: string
  gmail_message_id: string
  mailbox: string
  from_email: string | null
  subject: string | null
  received_at: string | null
  status: string
  is_lead: boolean | null
  confidence: number | null
  reasoning: string | null
  lead_id: string | null
  error: string | null
}

export interface EncodeJob {
  id: string
  source_url: string
  platform: string
  kind: string | null
  asset_id: string | null
  version_id: string | null
  slide_index: number | null
  status: string
  attempts: number
  output_key: string | null
  target_source: string
  bytes: number | null
  width: number | null
  height: number | null
  duration_sec: number | null
  video_kbps: number | null
  error: string | null
  created_at: string
  updated_at: string
}

export interface IntakeFile {
  id: string
  created_at: string
  form_id: string
  block_id: string
  filename: string
  url: string
  size_bytes: number
}

export interface IntakeForm {
  id: string
  created_at: string
  client_id: string
  template_key: string
  definition: unknown
  token: string
  status: string
  answers: unknown
  send_copy_to_client: boolean
  sent_at: string | null
  first_opened_at: string | null
  submitted_at: string | null
  reopened_at: string | null
  created_by: string | null
  title: string | null
  show_on_portal: boolean | null
  notify_emails: string[] | null
}

export interface IntakeSetting {
  id: number
  notify_emails: string
  updated_at: string
  updated_by: string | null
}

export interface IntakeTemplate {
  key: string
  definition: unknown
  updated_at: string
  updated_by: string | null
  id: string
}

export interface ItemComment {
  id: string
  created_at: string
  item_id: string
  parent_id: string | null
  author_id: string | null
  visibility: string
  body: string
  video_timestamp_sec: number | null
  assigned_to: string | null
  resolved: boolean
}

export interface JournalPost {
  id: string
  created_at: string
  updated_at: string
  slug: string
  title: string
  standfirst: string
  category: string
  cover_url: string
  read_mins: number
  published_at: string | null
  featured: boolean
  sections: unknown
  sort_order: number
  published: boolean
}

export interface Lead {
  source: string | null
  id: string
  created_at: string
  fname: string | null
  lname: string | null
  email: string | null
  phone: string | null
  biz: string | null
  model: string | null
  need: string | null
  budget: string | null
  timeline: string | null
}

export interface MonthlyCommitment {
  video_quota: number | null
  id: string
  created_at: string
  client_id: string
  month: number
  year: number
  reel_quota: number
  carousel_quota: number
  story_quota: number
  static_quota: number
  other_quota: number
  notes: string | null
}

export interface MonthlyUpdate {
  id: string
  created_at: string
  client_id: string
  month: number
  year: number
  definition: unknown
  token: string
  status: string
  answers: unknown
  notify_emails: string[] | null
  sent_at: string | null
  first_opened_at: string | null
  submitted_at: string | null
  reopened_at: string | null
  title: string
  created_by: string | null
}

export interface NewsletterSubscriber {
  id: string
  email: string
  source: string
  created_at: string
}

export interface NotificationLog {
  id: string
  created_at: string
  dedupe_key: string
  event_type: string
  recipient_id: string | null
  recipient_email: string
  subject: string
  body_html: string
  entity_type: string | null
  entity_id: string | null
  channel: string
  status: string
  sent_at: string | null
  error: string | null
  retry_count: number
  read_at: string | null
  claimed_at: string | null
}

export interface PostAnalytic {
  id: string
  item_id: string | null
  publish_job_id: string | null
  provider_post_id: string
  platform: string | null
  platform_post_url: string | null
  views: number | null
  reach: number | null
  impressions: number | null
  likes: number | null
  comments: number | null
  shares: number | null
  saves: number | null
  engagement_rate: number | null
  sync_status: string | null
  published_at: string | null
  synced_at: string
  raw: unknown
  source: string | null
}

export interface Project {
  gallery_urls: string | null
  website_url: string | null
  id: string
  created_at: string
  updated_at: string
  client_id: string | null
  slug: string
  name: string
  industry: string
  tag: string
  services: string
  description: string
  card_media_url: string
  hero_media_url: string
  result: string | null
  challenge: string
  approach: string
  outcome: string
  sort_order: number
  published: boolean
}

export interface ProviderWebhook {
  id: string
  provider: string
  provider_hook_id: string | null
  url: string
  events: unknown
  secret_encrypted: string | null
  active: boolean
  registered_by: string | null
  created_at: string
  updated_at: string
}

export interface PublishJob {
  id: string
  client_id: string | null
  content_item_id: string | null
  schedule_entry_id: string | null
  caption: string
  media: unknown
  targets: unknown
  scheduled_for: string | null
  timezone: string
  status: string
  request_id: string
  provider_post_id: string | null
  permalink: string | null
  error: string | null
  attempts: number
  created_by: string | null
  created_at: string
  updated_at: string
  published_at: string | null
}

export interface ReportSetting {
  id: string
  updated_at: string
  enabled: boolean
  recipients: string
  send_day: number
  data_from: string | null
  last_sent_for: string | null
}

export interface RoomInviteRequest {
  id: string
  name: string
  email: string
  about: string | null
  created_at: string
}

export interface ScanMailbox {
  refresh_token_encrypted: string | null
  connected_at: string | null
  connected_by: string | null
  email: string
  enabled: boolean
  label: string | null
  source: string
  created_at: string
  updated_at: string
  updated_by: string | null
  id: string
}

export interface ScanRun {
  id: string
  mailbox: string
  trigger: string
  status: string
  started_at: string
  finished_at: string | null
  scanned: number
  claimed: number
  leads_created: number
  skipped: number
  errors: number
  error: string | null
}

export interface ScanSetting {
  allow_self_connect: boolean | null
  id: number
  lookback_days: number
  max_messages: number
  min_confidence: number
  duplicate_window_days: number
  rules_only: boolean
  schedule_enabled: boolean
  blocked_domains: string
  blocked_senders: string
  updated_at: string
  updated_by: string | null
}

export interface ScheduleEntry {
  external_match_state: string | null
  id: string
  created_at: string
  item_id: string
  platform: string
  scheduled_at: string | null
  scheduler_id: string | null
  tool_url: string | null
  live_url: string | null
  publish_status: string
  published_at: string | null
}

export interface ScheduleNote {
  id: string
  client_id: string
  at: string
  text: string
  created_by: string | null
  created_at: string
  updated_at: string
}

export interface ShootProposal {
  batch_id: string | null
  id: string
  token: string
  client_id: string
  title: string
  starts_at: string
  ends_at: string
  location: string | null
  note: string | null
  send_to: string
  status: string
  created_by: string | null
  responded_at: string | null
  created_at: string
  notify_emails: string[] | null
  gcal_event_id: string | null
}

export interface SocialAccount {
  id: string
  client_id: string | null
  platform: string
  provider_account_id: string
  name: string | null
  username: string | null
  avatar_url: string | null
  active: boolean
  connected_at: string
  last_synced_at: string
}

export interface SocialPost {
  id: string
  client_id: string
  item_id: string
  version_id: string | null
  version_number: number | null
  slides: unknown
  caption: string | null
  per_channel: unknown
  channels: unknown
  scheduled_for: string | null
  timezone: string
  status: string
  publish_job_ids: unknown
  created_by: string | null
  created_at: string
  updated_at: string
  sent_at: string | null
  approved_at: string | null
  approved_by: string | null
  approval_mode: string | null
  note: string | null
}

export interface TeamInvite {
  id: string
  created_at: string
  email: string
  role: string
  employment_type: string
  timezone: string
  client_id: string | null
  assigned_client_ids: string
  invited_by: string | null
  clerk_invitation_id: string | null
  status: string
}

export interface TeamUserClient {
  team_user_id: string
  client_id: string
  assigned_at: string
  assigned_by: string | null
  id: string
}

export interface TeamUser {
  getting_started_dismissed_at: string | null
  getting_started_dismissed_role: string | null
  getting_started_dismissed_pages: unknown | null
  id: string
  created_at: string
  updated_at: string
  clerk_user_id: string | null
  email: string
  name: string
  role: string
  employment_type: string
  timezone: string
  workday_start: string
  workday_end: string
  client_id: string | null
  asana_user_gid: string | null
  notification_prefs: unknown
  active_status: boolean
}

export interface UserPageAccess {
  team_user_id: string
  href: string
  granted_at: string
  granted_by: string | null
  id: string
}

export interface VideoPreview {
  id: string
  source_url: string
  stream_uid: string | null
  state: string
  playback_hls: string | null
  thumbnail_url: string | null
  duration_sec: number | null
  width: number | null
  height: number | null
  error: string | null
  created_at: string
  updated_at: string
}

export interface WebhookDelivery {
  id: string
  provider: string
  event: string
  provider_event_id: string
  received_at: string
  handled: boolean
  note: string | null
}

export interface Website {
  id: string
}

export interface WorkKind {
  id: string
  created_at: string
  slug: string
  name: string
  default_roles: string
  uses_media: boolean
  color: string
  active: boolean
  sort_order: number
}

export interface WorkflowActivity {
  id: string
  created_at: string
  actor_id: string | null
  client_id: string | null
  entity_type: string
  entity_id: string
  action: string
  old_value: string | null
  new_value: string | null
  detail: string | null
}

export const TABLE_COLUMNS = {
  agency_credentials: ['id', 'created_at', 'updated_at', 'platform', 'label', 'username', 'secret_cipher', 'url', 'notes', 'updated_by', 'updated_by_name'],
  approvals: ['id', 'created_at', 'item_id', 'batch_id', 'approval_type', 'decided_by', 'decision', 'notes'],
  asana_events: ['id', 'dedup_key', 'created_at', 'ingested_at', 'source', 'user_gid', 'resource_gid', 'resource_type', 'action', 'change_field', 'project_gid', 'raw'],
  asana_project_map: ['project_gid', 'project_name', 'client_id', 'tracked', 'created_at', 'id'],
  asana_tasks: ['gid', 'name', 'assignee_gid', 'project_gid', 'completed', 'completed_at', 'due_on', 'modified_at', 'synced_at', 'permalink_url', 'id'],
  asana_webhooks: ['id', 'created_at', 'project_gid', 'webhook_gid', 'hook_secret', 'sync_token', 'last_heartbeat_at', 'last_event_at', 'last_error'],
  asset_clicks: ['id', 'asset_id', 'click_id', 'referrer', 'user_agent', 'clicked_at'],
  asset_versions: ['id', 'created_at', 'item_id', 'version_number', 'file_url', 'dropbox_url', 'drive_url', 'notes', 'uploaded_by', 'files', 'cover_url', 'trim_start', 'trim_end', 'source', 'source_drive_file_id'],
  assets: ['id', 'created_at', 'client_id', 'project_id', 'kind', 'orientation', 'purpose', 'url', 'alt'],
  assistant_chats: ['id', 'created_at', 'updated_at', 'clerk_user_id', 'title', 'messages'],
  assistant_prefs: ['clerk_user_id', 'email', 'instructions', 'updated_at', 'updated_by', 'id'],
  batch_comments: ['id', 'created_at', 'batch_id', 'author_id', 'body', 'assigned_to', 'resolved'],
  batches: ['status', 'concept', 'location', 'shot_list', 'planned_deliverables', 'reference_media', 'locked_at', 'locked_by', 'shot_at', 'proposal_id', 'share_board', 'board_name', 'last_edited_by', 'last_edited_at', 'canvas_cards', 'drive_folder_id', 'drive_url', 'shared_with_client', 'id', 'created_at', 'updated_at', 'client_id', 'title', 'description', 'shoot_date', 'month', 'year', 'owner_id'],
  board_comments: ['id', 'board_id', 'item_id', 'author_id', 'author_name', 'author_role', 'body', 'created_at', 'resolved_at'],
  board_items: ['id', 'board_id', 'kind', 'x', 'y', 'w', 'h', 'z', 'colour', 'text', 'url', 'label', 'child_board_id', 'column_title', 'parent_item_id', 'created_by', 'created_at', 'updated_at'],
  boards: ['id', 'client_id', 'parent_board_id', 'item_id', 'name', 'icon', 'colour', 'created_by', 'created_at', 'updated_at'],
  booking_availability: ['id', 'resource_id', 'weekday', 'start_min', 'end_min'],
  booking_blackouts: ['id', 'resource_id', 'day', 'reason'],
  booking_resources: ['id', 'created_at', 'label', 'email', 'timezone', 'active', 'space_id'],
  booking_seats: ['id'],
  booking_services: ['id', 'created_at', 'name', 'slug', 'description', 'duration_min', 'price_cents', 'currency', 'active', 'sort_order', 'policy_text', 'resource_id', 'lead_time_min', 'horizon_days', 'requires_payment', 'image_url', 'location', 'category', 'capacity'],
  bookings: ['id', 'created_at', 'service_id', 'resource_id', 'start_at', 'end_at', 'customer_name', 'customer_email', 'customer_phone', 'notes', 'status', 'payment_status', 'payment_ref', 'amount_cents', 'policy_agreed_at', 'checkout_ref', 'public_ref', 'seat_no', 'space_id'],
  calendar_accounts: ['email', 'refresh_token_encrypted', 'enabled', 'connected_at', 'connected_by', 'created_at', 'id'],
  claim_locks: ['id'],
  client_agreements: ['id', 'created_at', 'updated_at', 'client_id', 'deliverable_lines', 'services', 'notes', 'updated_by', 'start_date'],
  client_brand: ['client_id', 'updated_at', 'updated_by', 'profile', 'docs', 'scan_status', 'scan_done', 'scan_total', 'scan_message', 'scan_started_at', 'id'],
  client_contacts: ['id', 'created_at', 'updated_at', 'client_id', 'name', 'role', 'email', 'phone', 'is_primary', 'notes'],
  client_credentials: ['id', 'created_at', 'updated_at', 'client_id', 'platform', 'label', 'username', 'secret_cipher', 'url', 'notes', 'updated_by', 'updated_by_name'],
  client_notes: ['id', 'created_at', 'updated_at', 'client_id', 'body', 'author_id', 'author_name', 'visibility'],
  clients: ['brand_profile', 'brand_profile_updated_at', 'brand_profile_updated_by', 'timezone', 'website', 'source', 'share_token', 'social_profile_id', 'id', 'created_at', 'name', 'slug', 'industry', 'contact_name', 'email', 'phone', 'clerk_user_id', 'status', 'notes', 'instagram_locations', 'client_approval_required', 'drive_folder_id', 'drive_folder_origin'],
  content_applications: ['id', 'created_at', 'first_name', 'last_name', 'email', 'phone', 'business', 'industry', 'model_interest', 'content_needed', 'budget', 'timeline'],
  content_assets: ['id', 'client_id', 'title', 'platform', 'slug', 'dest_url', 'post_url', 'provider_post_id', 'source', 'offer_code', 'keyword', 'published_at', 'created_at'],
  content_items: ['group_id', 'drive_folder_id', 'drive_url', 'posting_approval_state', 'id', 'created_at', 'updated_at', 'client_id', 'batch_id', 'title', 'content_type', 'platform_targets', 'status', 'owner_id', 'due_date', 'priority', 'caption', 'client_approval_required', 'current_version_number', 'raw_assets_url', 'brief', 'raw_assets', 'scheduler_ids', 'brief_url', 'work_kind_id'],
  deliverable_groups: ['id', 'client_id', 'batch_id', 'content_type', 'title', 'target', 'work_kind_id', 'created_by', 'created_at', 'planned'],
  drive_connection: ['id', 'account_email', 'account_name', 'refresh_token_encrypted', 'root_name', 'root_folder_id', 'connected_by', 'connected_at', 'created_at', 'root_folder_name', 'root_owner_email', 'root_origin', 'root_picked_at', 'root_picked_by', 'clients_folder_id', 'root_account_changed'],
  drive_files: ['parent_id', 'name', 'uploaded_by', 'moved_at', 'id', 'item_id', 'client_id', 'source_url', 'target', 'drive_file_id', 'drive_url', 'bytes', 'created_at'],
  drive_uploads: ['id', 'upload_uri', 'name', 'parent_id', 'mime_type', 'size', 'received', 'client_id', 'status', 'drive_file_id', 'created_by', 'created_at', 'updated_at'],
  email_ingest_log: ['id', 'created_at', 'gmail_message_id', 'mailbox', 'from_email', 'subject', 'received_at', 'status', 'is_lead', 'confidence', 'reasoning', 'lead_id', 'error'],
  encode_jobs: ['id', 'source_url', 'platform', 'kind', 'asset_id', 'version_id', 'slide_index', 'status', 'attempts', 'output_key', 'target_source', 'bytes', 'width', 'height', 'duration_sec', 'video_kbps', 'error', 'created_at', 'updated_at'],
  intake_files: ['id', 'created_at', 'form_id', 'block_id', 'filename', 'url', 'size_bytes'],
  intake_forms: ['id', 'created_at', 'client_id', 'template_key', 'definition', 'token', 'status', 'answers', 'send_copy_to_client', 'sent_at', 'first_opened_at', 'submitted_at', 'reopened_at', 'created_by', 'title', 'show_on_portal', 'notify_emails'],
  intake_settings: ['id', 'notify_emails', 'updated_at', 'updated_by'],
  intake_templates: ['key', 'definition', 'updated_at', 'updated_by', 'id'],
  item_comments: ['id', 'created_at', 'item_id', 'parent_id', 'author_id', 'visibility', 'body', 'video_timestamp_sec', 'assigned_to', 'resolved'],
  journal_posts: ['id', 'created_at', 'updated_at', 'slug', 'title', 'standfirst', 'category', 'cover_url', 'read_mins', 'published_at', 'featured', 'sections', 'sort_order', 'published'],
  leads: ['source', 'id', 'created_at', 'fname', 'lname', 'email', 'phone', 'biz', 'model', 'need', 'budget', 'timeline'],
  monthly_commitments: ['video_quota', 'id', 'created_at', 'client_id', 'month', 'year', 'reel_quota', 'carousel_quota', 'story_quota', 'static_quota', 'other_quota', 'notes'],
  monthly_updates: ['id', 'created_at', 'client_id', 'month', 'year', 'definition', 'token', 'status', 'answers', 'notify_emails', 'sent_at', 'first_opened_at', 'submitted_at', 'reopened_at', 'title', 'created_by'],
  newsletter_subscribers: ['id', 'email', 'source', 'created_at'],
  notification_log: ['id', 'created_at', 'dedupe_key', 'event_type', 'recipient_id', 'recipient_email', 'subject', 'body_html', 'entity_type', 'entity_id', 'channel', 'status', 'sent_at', 'error', 'retry_count', 'read_at', 'claimed_at'],
  post_analytics: ['id', 'item_id', 'publish_job_id', 'provider_post_id', 'platform', 'platform_post_url', 'views', 'reach', 'impressions', 'likes', 'comments', 'shares', 'saves', 'engagement_rate', 'sync_status', 'published_at', 'synced_at', 'raw', 'source'],
  projects: ['gallery_urls', 'website_url', 'id', 'created_at', 'updated_at', 'client_id', 'slug', 'name', 'industry', 'tag', 'services', 'description', 'card_media_url', 'hero_media_url', 'result', 'challenge', 'approach', 'outcome', 'sort_order', 'published'],
  provider_webhooks: ['id', 'provider', 'provider_hook_id', 'url', 'events', 'secret_encrypted', 'active', 'registered_by', 'created_at', 'updated_at'],
  publish_jobs: ['id', 'client_id', 'content_item_id', 'schedule_entry_id', 'caption', 'media', 'targets', 'scheduled_for', 'timezone', 'status', 'request_id', 'provider_post_id', 'permalink', 'error', 'attempts', 'created_by', 'created_at', 'updated_at', 'published_at'],
  report_settings: ['id', 'updated_at', 'enabled', 'recipients', 'send_day', 'data_from', 'last_sent_for'],
  room_invite_requests: ['id', 'name', 'email', 'about', 'created_at'],
  scan_mailboxes: ['refresh_token_encrypted', 'connected_at', 'connected_by', 'email', 'enabled', 'label', 'source', 'created_at', 'updated_at', 'updated_by', 'id'],
  scan_runs: ['id', 'mailbox', 'trigger', 'status', 'started_at', 'finished_at', 'scanned', 'claimed', 'leads_created', 'skipped', 'errors', 'error'],
  scan_settings: ['allow_self_connect', 'id', 'lookback_days', 'max_messages', 'min_confidence', 'duplicate_window_days', 'rules_only', 'schedule_enabled', 'blocked_domains', 'blocked_senders', 'updated_at', 'updated_by'],
  schedule_entries: ['external_match_state', 'id', 'created_at', 'item_id', 'platform', 'scheduled_at', 'scheduler_id', 'tool_url', 'live_url', 'publish_status', 'published_at'],
  schedule_notes: ['id', 'client_id', 'at', 'text', 'created_by', 'created_at', 'updated_at'],
  shoot_proposals: ['batch_id', 'id', 'token', 'client_id', 'title', 'starts_at', 'ends_at', 'location', 'note', 'send_to', 'status', 'created_by', 'responded_at', 'created_at', 'notify_emails', 'gcal_event_id'],
  social_accounts: ['id', 'client_id', 'platform', 'provider_account_id', 'name', 'username', 'avatar_url', 'active', 'connected_at', 'last_synced_at'],
  social_posts: ['id', 'client_id', 'item_id', 'version_id', 'version_number', 'slides', 'caption', 'per_channel', 'channels', 'scheduled_for', 'timezone', 'status', 'publish_job_ids', 'created_by', 'created_at', 'updated_at', 'sent_at', 'approved_at', 'approved_by', 'approval_mode', 'note'],
  team_invites: ['id', 'created_at', 'email', 'role', 'employment_type', 'timezone', 'client_id', 'assigned_client_ids', 'invited_by', 'clerk_invitation_id', 'status'],
  team_user_clients: ['team_user_id', 'client_id', 'assigned_at', 'assigned_by', 'id'],
  team_users: ['getting_started_dismissed_at', 'getting_started_dismissed_role', 'getting_started_dismissed_pages', 'id', 'created_at', 'updated_at', 'clerk_user_id', 'email', 'name', 'role', 'employment_type', 'timezone', 'workday_start', 'workday_end', 'client_id', 'asana_user_gid', 'notification_prefs', 'active_status'],
  user_page_access: ['team_user_id', 'href', 'granted_at', 'granted_by', 'id'],
  video_previews: ['id', 'source_url', 'stream_uid', 'state', 'playback_hls', 'thumbnail_url', 'duration_sec', 'width', 'height', 'error', 'created_at', 'updated_at'],
  webhook_deliveries: ['id', 'provider', 'event', 'provider_event_id', 'received_at', 'handled', 'note'],
  website: ['id'],
  work_kinds: ['id', 'created_at', 'slug', 'name', 'default_roles', 'uses_media', 'color', 'active', 'sort_order'],
  workflow_activity: ['id', 'created_at', 'actor_id', 'client_id', 'entity_type', 'entity_id', 'action', 'old_value', 'new_value', 'detail'],
} as const satisfies Record<TableName, readonly string[]>

export const NULLABLE_COLUMNS = {
  agency_credentials: ['secret_cipher', 'updated_by'],
  approvals: ['item_id', 'batch_id', 'decided_by', 'notes'],
  asana_events: ['user_gid', 'change_field', 'project_gid'],
  asana_project_map: ['client_id'],
  asana_tasks: ['assignee_gid', 'project_gid', 'completed_at', 'due_on', 'modified_at', 'permalink_url'],
  asana_webhooks: ['webhook_gid', 'hook_secret', 'sync_token', 'last_heartbeat_at', 'last_event_at', 'last_error'],
  asset_clicks: ['referrer', 'user_agent'],
  asset_versions: ['notes', 'uploaded_by', 'files', 'cover_url', 'trim_start', 'trim_end', 'source', 'source_drive_file_id'],
  assets: ['client_id', 'project_id', 'orientation', 'purpose', 'alt'],
  assistant_chats: [],
  assistant_prefs: [],
  batch_comments: ['author_id', 'assigned_to', 'resolved'],
  batches: ['status', 'concept', 'location', 'shot_list', 'planned_deliverables', 'reference_media', 'locked_at', 'locked_by', 'shot_at', 'proposal_id', 'share_board', 'board_name', 'last_edited_by', 'last_edited_at', 'canvas_cards', 'drive_folder_id', 'drive_url', 'shared_with_client', 'description', 'shoot_date', 'month', 'year', 'owner_id'],
  board_comments: ['author_id', 'resolved_at'],
  board_items: ['colour', 'text', 'url', 'label', 'child_board_id', 'column_title', 'parent_item_id', 'created_by'],
  boards: ['parent_board_id', 'item_id', 'created_by'],
  booking_availability: [],
  booking_blackouts: ['reason'],
  booking_resources: ['email', 'space_id'],
  booking_seats: [],
  booking_services: ['description', 'policy_text', 'resource_id', 'lead_time_min', 'horizon_days', 'requires_payment', 'image_url', 'location', 'category', 'capacity'],
  bookings: ['service_id', 'customer_phone', 'notes', 'payment_ref', 'policy_agreed_at', 'checkout_ref', 'public_ref', 'seat_no', 'space_id'],
  calendar_accounts: ['refresh_token_encrypted', 'connected_at', 'connected_by'],
  claim_locks: [],
  client_agreements: ['notes', 'updated_by', 'start_date'],
  client_brand: ['scan_status', 'scan_done', 'scan_total', 'scan_message', 'scan_started_at'],
  client_contacts: [],
  client_credentials: ['secret_cipher', 'updated_by'],
  client_notes: ['author_id', 'visibility'],
  clients: ['brand_profile', 'brand_profile_updated_at', 'brand_profile_updated_by', 'timezone', 'website', 'source', 'share_token', 'social_profile_id', 'industry', 'contact_name', 'email', 'phone', 'clerk_user_id', 'notes', 'client_approval_required', 'drive_folder_id', 'drive_folder_origin'],
  content_applications: ['industry', 'model_interest', 'content_needed', 'budget', 'timeline'],
  content_assets: ['client_id', 'platform', 'dest_url', 'post_url', 'provider_post_id', 'offer_code', 'keyword', 'published_at'],
  content_items: ['group_id', 'drive_folder_id', 'drive_url', 'batch_id', 'owner_id', 'due_date', 'caption', 'raw_assets_url', 'brief', 'raw_assets', 'scheduler_ids', 'brief_url', 'work_kind_id'],
  deliverable_groups: ['batch_id', 'work_kind_id', 'created_by', 'planned'],
  drive_connection: ['account_email', 'account_name', 'refresh_token_encrypted', 'root_folder_id', 'connected_by', 'connected_at', 'root_folder_name', 'root_owner_email', 'root_origin', 'root_picked_at', 'root_picked_by', 'clients_folder_id', 'root_account_changed'],
  drive_files: ['parent_id', 'name', 'uploaded_by', 'moved_at', 'item_id', 'client_id', 'drive_file_id', 'drive_url', 'bytes'],
  drive_uploads: ['mime_type', 'size', 'client_id', 'drive_file_id', 'created_by'],
  email_ingest_log: ['from_email', 'subject', 'received_at', 'is_lead', 'confidence', 'reasoning', 'lead_id', 'error'],
  encode_jobs: ['kind', 'asset_id', 'version_id', 'slide_index', 'output_key', 'bytes', 'width', 'height', 'duration_sec', 'video_kbps', 'error'],
  intake_files: [],
  intake_forms: ['sent_at', 'first_opened_at', 'submitted_at', 'reopened_at', 'created_by', 'title', 'show_on_portal', 'notify_emails'],
  intake_settings: ['updated_by'],
  intake_templates: ['updated_by'],
  item_comments: ['parent_id', 'author_id', 'video_timestamp_sec', 'assigned_to'],
  journal_posts: ['published_at'],
  leads: ['source', 'fname', 'lname', 'email', 'phone', 'biz', 'model', 'need', 'budget', 'timeline'],
  monthly_commitments: ['video_quota', 'notes'],
  monthly_updates: ['notify_emails', 'sent_at', 'first_opened_at', 'submitted_at', 'reopened_at', 'created_by'],
  newsletter_subscribers: [],
  notification_log: ['recipient_id', 'entity_type', 'entity_id', 'sent_at', 'error', 'read_at', 'claimed_at'],
  post_analytics: ['item_id', 'publish_job_id', 'platform', 'platform_post_url', 'views', 'reach', 'impressions', 'likes', 'comments', 'shares', 'saves', 'engagement_rate', 'sync_status', 'published_at', 'source'],
  projects: ['gallery_urls', 'website_url', 'client_id', 'result'],
  provider_webhooks: ['provider_hook_id', 'secret_encrypted', 'registered_by'],
  publish_jobs: ['client_id', 'content_item_id', 'schedule_entry_id', 'scheduled_for', 'provider_post_id', 'permalink', 'error', 'created_by', 'published_at'],
  report_settings: ['data_from', 'last_sent_for'],
  room_invite_requests: ['about'],
  scan_mailboxes: ['refresh_token_encrypted', 'connected_at', 'connected_by', 'label', 'updated_by'],
  scan_runs: ['finished_at', 'error'],
  scan_settings: ['allow_self_connect', 'updated_by'],
  schedule_entries: ['external_match_state', 'scheduled_at', 'scheduler_id', 'tool_url', 'live_url', 'published_at'],
  schedule_notes: ['created_by'],
  shoot_proposals: ['batch_id', 'location', 'note', 'created_by', 'responded_at', 'notify_emails', 'gcal_event_id'],
  social_accounts: ['client_id', 'name', 'username', 'avatar_url'],
  social_posts: ['version_id', 'version_number', 'caption', 'scheduled_for', 'created_by', 'sent_at', 'approved_at', 'approved_by', 'approval_mode', 'note'],
  team_invites: ['client_id', 'invited_by', 'clerk_invitation_id'],
  team_user_clients: ['assigned_by'],
  team_users: ['getting_started_dismissed_at', 'getting_started_dismissed_role', 'getting_started_dismissed_pages', 'clerk_user_id', 'client_id', 'asana_user_gid'],
  user_page_access: ['granted_by'],
  video_previews: ['stream_uid', 'playback_hls', 'thumbnail_url', 'duration_sec', 'width', 'height', 'error'],
  webhook_deliveries: ['note'],
  website: [],
  work_kinds: [],
  workflow_activity: ['actor_id', 'client_id', 'old_value', 'new_value', 'detail'],
} as const satisfies Record<TableName, readonly string[]>

/**
 * json/jsonb columns. The Realtime Database stores no empty object or array, so
 * a column written as an empty object reads back missing; normalise() (lib/db.ts)
 * and snapshotToRows() (lib/db-client.ts) restore it — null when the column is
 * nullable, {} when it is not — or [] when the column is listed in
 * JSON_ARRAY_COLUMNS below.
 */
export const JSON_COLUMNS = {
  agency_credentials: [],
  approvals: [],
  asana_events: ['raw'],
  asana_project_map: [],
  asana_tasks: [],
  asana_webhooks: [],
  asset_clicks: [],
  asset_versions: ['files'],
  assets: [],
  assistant_chats: ['messages'],
  assistant_prefs: [],
  batch_comments: [],
  batches: ['shot_list', 'planned_deliverables', 'reference_media', 'canvas_cards'],
  board_comments: [],
  board_items: [],
  boards: [],
  booking_availability: [],
  booking_blackouts: [],
  booking_resources: [],
  booking_seats: [],
  booking_services: [],
  bookings: [],
  calendar_accounts: [],
  claim_locks: [],
  client_agreements: ['deliverable_lines', 'services'],
  client_brand: ['profile', 'docs'],
  client_contacts: [],
  client_credentials: [],
  client_notes: [],
  clients: ['brand_profile', 'instagram_locations'],
  content_applications: [],
  content_assets: [],
  content_items: ['raw_assets', 'scheduler_ids'],
  deliverable_groups: ['planned'],
  drive_connection: [],
  drive_files: [],
  drive_uploads: [],
  email_ingest_log: [],
  encode_jobs: [],
  intake_files: [],
  intake_forms: ['definition', 'answers'],
  intake_settings: [],
  intake_templates: ['definition'],
  item_comments: [],
  journal_posts: ['sections'],
  leads: [],
  monthly_commitments: [],
  monthly_updates: ['definition', 'answers'],
  newsletter_subscribers: [],
  notification_log: [],
  post_analytics: ['raw'],
  projects: [],
  provider_webhooks: ['events'],
  publish_jobs: ['media', 'targets'],
  report_settings: [],
  room_invite_requests: [],
  scan_mailboxes: [],
  scan_runs: [],
  scan_settings: [],
  schedule_entries: [],
  schedule_notes: [],
  shoot_proposals: [],
  social_accounts: [],
  social_posts: ['slides', 'per_channel', 'channels', 'publish_job_ids'],
  team_invites: [],
  team_user_clients: [],
  team_users: ['getting_started_dismissed_pages', 'notification_prefs'],
  user_page_access: [],
  video_previews: [],
  webhook_deliveries: [],
  website: [],
  work_kinds: [],
  workflow_activity: [],
} as const satisfies Record<TableName, readonly string[]>

/**
 * The subset of JSON_COLUMNS whose Postgres default was a JSON ARRAY
 * (default '[]'::jsonb). Restoring one of these as {} would be worse than
 * leaving it missing — spreading a plain object into an array throws, where
 * undefined was absorbed by the callers' \u0060?? []\u0060.
 */
export const JSON_ARRAY_COLUMNS = {
  agency_credentials: [],
  approvals: [],
  asana_events: [],
  asana_project_map: [],
  asana_tasks: [],
  asana_webhooks: [],
  asset_clicks: [],
  asset_versions: ['files'],
  assets: [],
  assistant_chats: ['messages'],
  assistant_prefs: [],
  batch_comments: [],
  batches: ['shot_list', 'planned_deliverables', 'reference_media', 'canvas_cards'],
  board_comments: [],
  board_items: [],
  boards: [],
  booking_availability: [],
  booking_blackouts: [],
  booking_resources: [],
  booking_seats: [],
  booking_services: [],
  bookings: [],
  calendar_accounts: [],
  claim_locks: [],
  client_agreements: ['deliverable_lines', 'services'],
  client_brand: ['docs'],
  client_contacts: [],
  client_credentials: [],
  client_notes: [],
  clients: ['instagram_locations'],
  content_applications: [],
  content_assets: [],
  content_items: ['raw_assets', 'scheduler_ids'],
  deliverable_groups: [],
  drive_connection: [],
  drive_files: [],
  drive_uploads: [],
  email_ingest_log: [],
  encode_jobs: [],
  intake_files: [],
  intake_forms: [],
  intake_settings: [],
  intake_templates: [],
  item_comments: [],
  journal_posts: ['sections'],
  leads: [],
  monthly_commitments: [],
  monthly_updates: [],
  newsletter_subscribers: [],
  notification_log: [],
  post_analytics: [],
  projects: [],
  provider_webhooks: ['events'],
  publish_jobs: ['media', 'targets'],
  report_settings: [],
  room_invite_requests: [],
  scan_mailboxes: [],
  scan_runs: [],
  scan_settings: [],
  schedule_entries: [],
  schedule_notes: [],
  shoot_proposals: [],
  social_accounts: [],
  social_posts: ['slides', 'channels', 'publish_job_ids'],
  team_invites: [],
  team_user_clients: [],
  team_users: ['getting_started_dismissed_pages'],
  user_page_access: [],
  video_previews: [],
  webhook_deliveries: [],
  website: [],
  work_kinds: [],
  workflow_activity: [],
} as const satisfies Record<TableName, readonly string[]>

export const UPDATED_AT_TABLES: ReadonlySet<TableName> = new Set<TableName>(['agency_credentials', 'batches', 'board_items', 'boards', 'client_agreements', 'client_contacts', 'client_credentials', 'client_notes', 'content_items', 'drive_uploads', 'encode_jobs', 'journal_posts', 'projects', 'report_settings', 'schedule_notes', 'social_posts', 'team_users'])

export function encodeKey(s: string): string {
  return s.replace(/[.#$\[\]\/%]/g, ch => '%' + ch.charCodeAt(0).toString(16).toUpperCase().padStart(2, '0'))
}

/** Tables whose Postgres key was not a uuid `id`. The id stored in RTDB is derived from the row. */
export const NATURAL_KEYS: Partial<Record<TableName, (row: any) => string>> = {
  team_user_clients: r => `${r.team_user_id}__${r.client_id}`,
  user_page_access: r => `${r.team_user_id}__${encodeKey(r.href)}`,
  asset_versions: r => `${r.item_id}__${r.version_number}`,
  client_brand: r => r.client_id,
  drive_connection: () => 'team',
  scan_settings: () => 'singleton',
  intake_settings: () => 'singleton',
  assistant_prefs: r => r.clerk_user_id,
  intake_templates: r => encodeKey(r.key),
  scan_mailboxes: r => encodeKey(r.email),
  calendar_accounts: r => encodeKey(r.email),
  asana_project_map: r => r.project_gid,
  asana_tasks: r => r.gid,
  asana_webhooks: r => r.webhook_gid ?? r.id,
}
